name: 'Install dependencies'
description: 'Prepare repository and all dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set bun
      uses: oven-sh/setup-bun@main

    - name: Install dependencies
      shell: bash
      run: bun install
