packages:
  - apps/**

catalog:
  '@biomejs/biome': ^2.3.8
  '@cloudflare/puppeteer': ^1.0.4
  '@cloudflare/vite-plugin': ^1.15.3
  '@cloudflare/vitest-pool-workers': ^0.10.11
  '@cloudflare/workers-types': ^4.20251202.0
  '@hono/zod-validator': ^0.7.5
  '@iconify/json': ^2.2.413
  '@svgr/core': ^8.1.0
  '@svgr/plugin-jsx': ^8.1.0
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/devtools-vite': ^0.3.11
  '@tanstack/query-async-storage-persister': ^5.90.13
  '@tanstack/react-devtools': ^0.8.2
  '@tanstack/react-query': ^5.90.11
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-query-persist-client': ^5.90.13
  '@tanstack/react-router': ^1.139.12
  '@tanstack/react-router-devtools': ^1.139.12
  '@tanstack/react-router-ssr-query': ^1.139.12
  '@tanstack/react-start': ^1.139.12
  '@tanstack/router-plugin': ^1.139.12
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.1
  abitype: ^1.2.0
  cva: ^1.0.0-beta.4
  eruda: ^3.4.3
  globals: ^16.5.0
  ox: ^0.9.17
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tempo.ts: ~0.7.5
  tw-animate-css: ^1.4.0
  typed-query-selector: ^2.12.0
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  viem: ^2.40.3
  vite: npm:rolldown-vite@latest
  vite-tsconfig-paths: ^5.1.4
  vitest: 3.2.4
  wagmi: ^3.0.2
  wrangler: ^4.51.0
  zod: ^4.1.13

catalogMode: strict
