/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTxHashRouteImport } from './routes/_layout/tx/$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutDemoTxRouteImport } from './routes/_layout/demo/tx'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutAccountAddressRouteImport } from './routes/_layout/account/$address'
import { Route as ApiTokenAddressRouteRouteImport } from './routes/api/token/$address/route'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoTxRoute = LayoutDemoTxRouteImport.update({
  id: '/demo/tx',
  path: '/demo/tx',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountAddressRoute = LayoutAccountAddressRouteImport.update({
  id: '/account/$address',
  path: '/account/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTokenAddressRouteRoute = ApiTokenAddressRouteRouteImport.update({
  id: '/api/token/$address',
  path: '/api/token/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/api/token/$address': typeof ApiTokenAddressRouteRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/api/token/$address': typeof ApiTokenAddressRouteRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/api/token/$address': typeof ApiTokenAddressRouteRoute
  '/_layout/account/$address': typeof LayoutAccountAddressRoute
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/demo/tx': typeof LayoutDemoTxRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/token/$address'
    | '/account/$address'
    | '/block/$id'
    | '/demo/tx'
    | '/token/$address'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/token/$address'
    | '/account/$address'
    | '/block/$id'
    | '/demo/tx'
    | '/token/$address'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/api/token/$address'
    | '/_layout/account/$address'
    | '/_layout/block/$id'
    | '/_layout/demo/tx'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiTokenAddressRouteRoute: typeof ApiTokenAddressRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/tx': {
      id: '/_layout/demo/tx'
      path: '/demo/tx'
      fullPath: '/demo/tx'
      preLoaderRoute: typeof LayoutDemoTxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/$address': {
      id: '/_layout/account/$address'
      path: '/account/$address'
      fullPath: '/account/$address'
      preLoaderRoute: typeof LayoutAccountAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/token/$address': {
      id: '/api/token/$address'
      path: '/api/token/$address'
      fullPath: '/api/token/$address'
      preLoaderRoute: typeof ApiTokenAddressRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountAddressRoute: typeof LayoutAccountAddressRoute
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutDemoTxRoute: typeof LayoutDemoTxRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutTxHashRoute: typeof LayoutTxHashRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountAddressRoute: LayoutAccountAddressRoute,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutDemoTxRoute: LayoutDemoTxRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutTxHashRoute: LayoutTxHashRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiTokenAddressRouteRoute: ApiTokenAddressRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
