/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutValueRouteImport } from './routes/_layout/$value'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutReceiptHashRouteImport } from './routes/_layout/receipt/$hash'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutApiHealthRouteImport } from './routes/_layout/api/health'
import { Route as LayoutAccountAddressRouteImport } from './routes/_layout/account/$address'
import { Route as LayoutApiAddressAddressRouteImport } from './routes/_layout/api/address/$address'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutValueRoute = LayoutValueRouteImport.update({
  id: '/$value',
  path: '/$value',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiptHashRoute = LayoutReceiptHashRouteImport.update({
  id: '/receipt/$hash',
  path: '/receipt/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiHealthRoute = LayoutApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountAddressRoute = LayoutAccountAddressRouteImport.update({
  id: '/account/$address',
  path: '/account/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiAddressAddressRoute = LayoutApiAddressAddressRouteImport.update({
  id: '/api/address/$address',
  path: '/api/address/$address',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$value': typeof LayoutValueRoute
  '/': typeof LayoutIndexRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/api/health': typeof LayoutApiHealthRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/api/address/$address': typeof LayoutApiAddressAddressRoute
}
export interface FileRoutesByTo {
  '/$value': typeof LayoutValueRoute
  '/': typeof LayoutIndexRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/api/health': typeof LayoutApiHealthRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/api/address/$address': typeof LayoutApiAddressAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$value': typeof LayoutValueRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account/$address': typeof LayoutAccountAddressRoute
  '/_layout/api/health': typeof LayoutApiHealthRoute
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/receipt/$hash': typeof LayoutReceiptHashRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/api/address/$address': typeof LayoutApiAddressAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$value'
    | '/'
    | '/account/$address'
    | '/api/health'
    | '/block/$id'
    | '/receipt/$hash'
    | '/token/$address'
    | '/api/address/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$value'
    | '/'
    | '/account/$address'
    | '/api/health'
    | '/block/$id'
    | '/receipt/$hash'
    | '/token/$address'
    | '/api/address/$address'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$value'
    | '/_layout/'
    | '/_layout/account/$address'
    | '/_layout/api/health'
    | '/_layout/block/$id'
    | '/_layout/receipt/$hash'
    | '/_layout/token/$address'
    | '/_layout/api/address/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$value': {
      id: '/_layout/$value'
      path: '/$value'
      fullPath: '/$value'
      preLoaderRoute: typeof LayoutValueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receipt/$hash': {
      id: '/_layout/receipt/$hash'
      path: '/receipt/$hash'
      fullPath: '/receipt/$hash'
      preLoaderRoute: typeof LayoutReceiptHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api/health': {
      id: '/_layout/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof LayoutApiHealthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/$address': {
      id: '/_layout/account/$address'
      path: '/account/$address'
      fullPath: '/account/$address'
      preLoaderRoute: typeof LayoutAccountAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api/address/$address': {
      id: '/_layout/api/address/$address'
      path: '/api/address/$address'
      fullPath: '/api/address/$address'
      preLoaderRoute: typeof LayoutApiAddressAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutValueRoute: typeof LayoutValueRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountAddressRoute: typeof LayoutAccountAddressRoute
  LayoutApiHealthRoute: typeof LayoutApiHealthRoute
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutReceiptHashRoute: typeof LayoutReceiptHashRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutApiAddressAddressRoute: typeof LayoutApiAddressAddressRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutValueRoute: LayoutValueRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountAddressRoute: LayoutAccountAddressRoute,
  LayoutApiHealthRoute: LayoutApiHealthRoute,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutReceiptHashRoute: LayoutReceiptHashRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutApiAddressAddressRoute: LayoutApiAddressAddressRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
