/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LayoutTxHashRouteImport } from './routes/_layout/tx/$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutAccountAddressRouteImport } from './routes/_layout/account/$address'
import { Route as ApiAccountAddressRouteRouteImport } from './routes/api/account/$address/route'
import { Route as ApiAccountAddressTotalValueRouteImport } from './routes/api/account/$address/total-value'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountAddressRoute = LayoutAccountAddressRouteImport.update({
  id: '/account/$address',
  path: '/account/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAccountAddressRouteRoute = ApiAccountAddressRouteRouteImport.update({
  id: '/api/account/$address',
  path: '/api/account/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountAddressTotalValueRoute =
  ApiAccountAddressTotalValueRouteImport.update({
    id: '/total-value',
    path: '/total-value',
    getParentRoute: () => ApiAccountAddressRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/health': typeof ApiHealthRoute
  '/': typeof LayoutIndexRoute
  '/api/account/$address': typeof ApiAccountAddressRouteRouteWithChildren
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
  '/api/account/$address/total-value': typeof ApiAccountAddressTotalValueRoute
}
export interface FileRoutesByTo {
  '/api/health': typeof ApiHealthRoute
  '/': typeof LayoutIndexRoute
  '/api/account/$address': typeof ApiAccountAddressRouteRouteWithChildren
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
  '/api/account/$address/total-value': typeof ApiAccountAddressTotalValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_layout/': typeof LayoutIndexRoute
  '/api/account/$address': typeof ApiAccountAddressRouteRouteWithChildren
  '/_layout/account/$address': typeof LayoutAccountAddressRoute
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/tx/$hash': typeof LayoutTxHashRoute
  '/api/account/$address/total-value': typeof ApiAccountAddressTotalValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/health'
    | '/'
    | '/api/account/$address'
    | '/account/$address'
    | '/block/$id'
    | '/token/$address'
    | '/tx/$hash'
    | '/api/account/$address/total-value'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/health'
    | '/'
    | '/api/account/$address'
    | '/account/$address'
    | '/block/$id'
    | '/token/$address'
    | '/tx/$hash'
    | '/api/account/$address/total-value'
  id:
    | '__root__'
    | '/_layout'
    | '/api/health'
    | '/_layout/'
    | '/api/account/$address'
    | '/_layout/account/$address'
    | '/_layout/block/$id'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
    | '/api/account/$address/total-value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAccountAddressRouteRoute: typeof ApiAccountAddressRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/$address': {
      id: '/_layout/account/$address'
      path: '/account/$address'
      fullPath: '/account/$address'
      preLoaderRoute: typeof LayoutAccountAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/account/$address': {
      id: '/api/account/$address'
      path: '/api/account/$address'
      fullPath: '/api/account/$address'
      preLoaderRoute: typeof ApiAccountAddressRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/$address/total-value': {
      id: '/api/account/$address/total-value'
      path: '/total-value'
      fullPath: '/api/account/$address/total-value'
      preLoaderRoute: typeof ApiAccountAddressTotalValueRouteImport
      parentRoute: typeof ApiAccountAddressRouteRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountAddressRoute: typeof LayoutAccountAddressRoute
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutTxHashRoute: typeof LayoutTxHashRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountAddressRoute: LayoutAccountAddressRoute,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutTxHashRoute: LayoutTxHashRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ApiAccountAddressRouteRouteChildren {
  ApiAccountAddressTotalValueRoute: typeof ApiAccountAddressTotalValueRoute
}

const ApiAccountAddressRouteRouteChildren: ApiAccountAddressRouteRouteChildren =
  {
    ApiAccountAddressTotalValueRoute: ApiAccountAddressTotalValueRoute,
  }

const ApiAccountAddressRouteRouteWithChildren =
  ApiAccountAddressRouteRoute._addFileChildren(
    ApiAccountAddressRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAccountAddressRouteRoute: ApiAccountAddressRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
